import { Compass, Flag, Landmark, Sprout, Target, Users } from 'lucide-react';
import '../public-pages.css';

export const metadata = { title: 'Profil Desa', description: 'Sejarah, visi, misi, dan kondisi wilayah Desa Margo Mulyo.' };
const missions = ['Meningkatkan kualitas sumber daya manusia melalui pendidikan, kesehatan, dan keagamaan.', 'Mengembangkan sektor pertanian, perkebunan, dan UMKM untuk kesejahteraan warga.', 'Mewujudkan tata kelola pemerintahan desa yang transparan dan responsif.', 'Membangun infrastruktur desa secara merata dan berkelanjutan.', 'Melestarikan budaya, kearifan lokal, dan semangat gotong royong.'];

export default function ProfilPage() {
  return <>
    <header className="page-hero" data-index="01"><div className="container"><div className="page-crumb">Beranda <span>/</span> Profil Desa</div><h1>Mengenal Margo Mulyo lebih dekat.</h1><p>Sejarah perjalanan, arah pembangunan, dan karakter wilayah yang membentuk kehidupan masyarakat desa.</p></div></header>
    <section className="content-section"><div className="container split-intro"><div><span className="eyebrow">Sejarah desa</span><h2>Berawal dari semangat membuka kehidupan baru.</h2></div><div className="prose"><p>Desa Margo Mulyo berkembang melalui program transmigrasi dari Pulau Jawa ke Provinsi Lampung. Kawasan yang dahulu berupa hutan dan lahan pertanian dibuka bertahap oleh para pendatang, lalu tumbuh menjadi permukiman melalui kerja bersama.</p><p>Masyarakat membangun rumah, lahan pertanian, fasilitas umum, dan kehidupan sosial dengan semangat gotong royong. Seiring berkembangnya jumlah penduduk dan aktivitas ekonomi, wilayah ini menjadi desa definitif bernama Margo Mulyo.</p><div className="quote-card"><p>“Margo” berarti jalan, sementara “Mulyo” berarti mulia atau sejahtera—jalan menuju kehidupan yang lebih baik.</p></div><p>Hari ini, Margo Mulyo terus berkembang sebagai desa agraris dengan potensi pertanian, perkebunan, dan usaha mikro masyarakat.</p></div></div></section>
    <section className="content-section content-section--cream"><div className="container"><div className="section-heading"><span className="eyebrow">Karakter desa</span><h2>Kekuatan yang tumbuh dari masyarakat.</h2></div><div className="feature-grid"><div className="feature-card"><span className="feature-icon"><Sprout /></span><h3>Desa Agraris</h3><p>Pertanian dan perkebunan menjadi penopang utama ekonomi keluarga.</p></div><div className="feature-card"><span className="feature-icon"><Users /></span><h3>Gotong Royong</h3><p>Kerja bersama menjadi nilai penting dalam pembangunan dan kehidupan sosial.</p></div><div className="feature-card"><span className="feature-icon"><Landmark /></span><h3>Tata Kelola</h3><p>Pemerintahan desa diarahkan untuk terbuka, melayani, dan bertanggung jawab.</p></div></div></div></section>
    <section className="content-section content-section--green"><div className="container"><div className="section-heading"><span className="eyebrow">Arah pembangunan</span><h2>Visi dan misi desa.</h2></div><div className="vision-grid"><div className="vision-card"><span className="feature-icon"><Target /></span><div><h3>Visi</h3><p>Terwujudnya Desa Margo Mulyo yang mandiri, sejahtera, agamis, dan berbudaya melalui pembangunan pertanian berkelanjutan serta tata kelola pemerintahan yang baik.</p></div></div><div className="mission-card"><h3><Flag size={22} /> Misi</h3><div className="mission-list">{missions.map((mission,index)=><div className="mission-item" key={mission}><span>0{index+1}</span><p>{mission}</p></div>)}</div></div></div></div></section>
    <section className="content-section"><div className="container"><div className="section-heading"><span className="eyebrow">Wilayah & administrasi</span><h2>Berada di jantung Kecamatan Tegineneng.</h2><p>Desa Margo Mulyo merupakan bagian dari Kabupaten Pesawaran, Provinsi Lampung.</p></div><div className="info-grid"><div className="info-row"><span>Luas wilayah</span><strong>6,89 km²</strong></div><div className="info-row"><span>Jumlah dusun</span><strong>6 dusun</strong></div><div className="info-row"><span>Kecamatan</span><strong>Tegineneng</strong></div><div className="info-row"><span>Kabupaten</span><strong>Pesawaran</strong></div><div className="info-row"><span>Provinsi</span><strong>Lampung</strong></div><div className="info-row"><span>Kode wilayah</span><strong>18.09.03.2012</strong></div><div className="info-row"><span>Jarak ke kecamatan</span><strong>± 8 km</strong></div><div className="info-row"><span>Jarak ke kabupaten</span><strong>± 34 km</strong></div></div><div className="notice"><Compass size={16} /> Data profil akan diperbarui secara berkala melalui sistem informasi desa.</div></div></section>
  </>;
}
