import { ArrowRight, Baby, BadgeCheck, HeartHandshake, Home, MoveRight, Store } from 'lucide-react';
import '../public-pages.css';

export const metadata = {
  title: 'Layanan Desa',
  description: 'Informasi layanan administrasi Pemerintah Desa Margomulyo, Tegineneng, termasuk pengantar KTP, KK, domisili, dan keterangan usaha.',
  alternates: { canonical: '/layanan' },
};
const services = [{icon:BadgeCheck,title:'Surat Pengantar KTP / KK',text:'Pengantar untuk penerbitan atau perubahan dokumen kependudukan.'},{icon:Home,title:'Surat Keterangan Domisili',text:'Keterangan resmi alamat tempat tinggal warga di wilayah desa.'},{icon:MoveRight,title:'Surat Pindah Datang',text:'Administrasi perpindahan penduduk masuk maupun keluar desa.'},{icon:HeartHandshake,title:'Surat Keterangan Tidak Mampu',text:'Dokumen pendukung untuk kebutuhan layanan sosial dan pendidikan.'},{icon:Baby,title:'Surat Keterangan Kelahiran',text:'Pengantar pencatatan kelahiran untuk proses dokumen kependudukan.'},{icon:Store,title:'Keterangan Usaha',text:'Surat keterangan bagi warga yang menjalankan kegiatan usaha.'}];
export default function LayananPage(){return <><header className="page-hero" data-index="03"><div className="container"><div className="page-crumb">Beranda <span>/</span> Layanan</div><h1>Pelayanan yang jelas dan mudah.</h1><p>Temukan jenis layanan administrasi, persyaratan awal, serta alur pengurusan dokumen di kantor desa.</p></div></header><section className="content-section surface-grid"><div className="container"><div className="section-heading"><span className="eyebrow">Administrasi warga</span><h2>Layanan yang tersedia.</h2><p>Siapkan KTP dan Kartu Keluarga asli atau salinan sebagai dokumen dasar. Persyaratan tambahan menyesuaikan jenis layanan.</p></div><div className="service-list">{services.map(({icon:Icon,title,text})=><div className="service-detail" key={title}><Icon size={23}/><div><h2>{title}</h2><p>{text}</p></div><ArrowRight size={18}/></div>)}</div></div></section><section className="content-section content-section--green"><div className="container"><div className="section-heading"><span className="eyebrow">Alur pelayanan</span><h2>Empat langkah sederhana.</h2></div><div className="steps"><div className="step"><h3>Siapkan berkas</h3><p>Pastikan dokumen dasar dan persyaratan pendukung telah lengkap.</p></div><div className="step"><h3>Datang ke kantor</h3><p>Ambil antrean dan sampaikan kebutuhan kepada petugas pelayanan.</p></div><div className="step"><h3>Verifikasi data</h3><p>Petugas memeriksa kelengkapan dan kesesuaian data warga.</p></div><div className="step"><h3>Dokumen diproses</h3><p>Dokumen diterbitkan sesuai jenis layanan dan waktu penyelesaian.</p></div></div></div></section></>}
