import Link from 'next/link';
import { ArrowRight, BarChart3, FileText, Images, Plus, Radio, UserRound, Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

export default async function AdminDashboard(){
  const supabase=await createClient();
  const [news,gallery,stats,published]=await Promise.all([supabase.from('news_articles').select('*',{count:'exact',head:true}),supabase.from('gallery_items').select('*',{count:'exact',head:true}),supabase.from('population_stats').select('*',{count:'exact',head:true}),supabase.from('news_articles').select('*',{count:'exact',head:true}).eq('is_published',true)]);
  const cards=[{label:'Total berita',value:news.count||0,icon:FileText,href:'/admin/berita'},{label:'Berita terbit',value:published.count||0,icon:Radio,href:'/admin/berita'},{label:'Foto galeri',value:gallery.count||0,icon:Images,href:'/admin/galeri'},{label:'Data statistik',value:stats.count||0,icon:BarChart3,href:'/admin/statistik'}];
  return <main className="admin-main"><header className="admin-page-head"><div><span>Dashboard</span><h1>Selamat datang di panel desa.</h1><p>Kelola informasi yang tampil pada website resmi Margomulyo.</p></div><Link href="/admin/berita/baru" className="admin-button admin-button--primary"><Plus size={17}/> Tulis berita</Link></header><section className="admin-stat-grid">{cards.map(({label,value,icon:Icon,href})=><Link href={href} className="admin-stat-card" key={label}><div><span>{label}</span><strong>{value.toLocaleString('id-ID')}</strong></div><Icon size={23}/></Link>)}</section><section className="admin-grid-two"><div className="admin-panel"><div className="panel-head"><div><span>Mulai bekerja</span><h2>Aksi cepat</h2></div></div><div className="quick-actions"><Link href="/admin/berita/baru"><FileText/><div><strong>Buat berita baru</strong><span>Tulis dan publikasikan kabar desa</span></div><ArrowRight/></Link><Link href="/admin/galeri"><Images/><div><strong>Tambah galeri</strong><span>Dokumentasikan kegiatan terbaru</span></div><ArrowRight/></Link><Link href="/admin/kepala-desa"><UserRound/><div><strong>Kelola kepala desa</strong><span>Atur foto, periode, dan profil kepemimpinan</span></div><ArrowRight/></Link><Link href="/admin/statistik"><BarChart3/><div><strong>Perbarui statistik</strong><span>Catat data kependudukan</span></div><ArrowRight/></Link></div></div><div className="admin-panel admin-guide"><div className="panel-head"><div><span>Status sistem</span><h2>Website publik</h2></div><i>Aktif</i></div><div className="guide-visual"><Users size={30}/><strong>Informasi untuk seluruh warga</strong><p>Pastikan data yang dipublikasikan telah diverifikasi dan tidak memuat informasi pribadi warga.</p></div></div></section></main>
}
